#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sets up buying Coins (docs/specs/buy-coins.md): Supabase, Vercel, Stripe test mode.
# Run from the repo root: scripts/setup-coins.sh
cd "$(dirname "$0")/.."
ENV_FILE=.env.local   # git-ignored; the real values live in Vercel
TOTAL_STAGES=8

banner "Goofy Sponge Walker · Coins setup (Stripe test mode)"

stage "Pick the game's address"
say "The game and its payment functions run on Vercel, on a subdomain of your other site."
note "Example: https://goofy.yoursite.nl (no slash at the end)."
ask SITE_URL "Full address of the game:"
SITE_URL="${SITE_URL%/}"
write_env SITE_URL "$SITE_URL"

stage "Supabase: create the project and copy its keys"
open_url "https://supabase.com/dashboard/projects"
step "Click 'New project'. Pick a name (goofy-sponge-walker), a database password and a region in the EU."
step "Wait until the project is ready (about a minute)."
step "Open Project Settings → Data API (or API) and copy the Project URL (https://….supabase.co)."
ask SUPABASE_URL "Paste the Project URL:"
step "Open Project Settings → API Keys. If you only see new-style keys, open the 'Legacy API keys' tab."
step "Copy the 'anon' 'public' key. It is safe to show in the browser."
ask SUPABASE_ANON_KEY "Paste the anon key:"
step "Reveal and copy the 'service_role' key. Keep this one secret: it can read and write everything."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the service_role key:"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

stage "Supabase: create the Coin ledger table and sign-in links"
if command -v pbcopy >/dev/null 2>&1; then pbcopy < supabase/schema.sql; say "supabase/schema.sql is copied to your clipboard."
else say "Copy the contents of supabase/schema.sql."; fi
REF="${SUPABASE_URL#https://}"; REF="${REF%%.*}"   # project ref: the first part of the URL
open_url "https://supabase.com/dashboard/project/$REF/sql/new"
step "In the SQL Editor, paste into a new query and click Run. It should say 'Success. No rows returned'."
pause "Press Enter when the query has run"
step "Open Authentication → URL Configuration."
step "Set Site URL to: $SITE_URL"
step "Under Redirect URLs, add: $SITE_URL/** and http://localhost:3000/**"
step "Authentication → Sign In / Providers: check that Email is enabled (magic links are on by default)."
pause "Press Enter when that is saved"

stage "Vercel: host the game on your subdomain"
open_url "https://vercel.com/new"
step "Import the GitHub repo D-Klaassen/goofy-sponge-walker."
step "Framework preset: Other. Leave the build command empty. Click Deploy."
step "When it's live, open the project → Settings → Domains → Add: ${SITE_URL#https://}"
step "Vercel shows a CNAME record. Add it in the DNS of your other site (name = the subdomain, value as Vercel shows it)."
note "DNS can take a few minutes. Vercel shows 'Valid Configuration' when it's done."
pause "Press Enter when the domain is added (it may still be checking)"

stage "Stripe: test key and iDEAL"
warn "Make sure the dashboard is in Test mode (toggle top right, or a 'Sandbox')."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the Secret key row, click Reveal test key and copy it (starts with sk_test_)."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
[[ "$STRIPE_SECRET_KEY" == sk_test_* ]] || warn "That doesn't start with sk_test_. Use a test key until going live."
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
open_url "https://dashboard.stripe.com/test/settings/payment_methods"
step "Turn on iDEAL (cards are on already)."
note "The waiver checkbox is in the game's shop and links to $SITE_URL/terms, so Stripe needs no terms link."
pause "Press Enter when iDEAL is on"

stage "Stripe: webhook for payments, refunds and disputes"
open_url "https://dashboard.stripe.com/test/webhooks"
step "Add an endpoint (or 'Add destination' → Webhook endpoint)."
step "Endpoint URL: $SITE_URL/api/webhook"
step "Select these 4 events:"
note "    checkout.session.completed"
note "    checkout.session.async_payment_succeeded"
note "    charge.refunded"
note "    charge.dispute.created"
step "Save, then reveal and copy the Signing secret (starts with whsec_)."
ask_secret STRIPE_WEBHOOK_SECRET "Paste the signing secret:"
write_env STRIPE_WEBHOOK_SECRET "$STRIPE_WEBHOOK_SECRET"

stage "Vercel: store the six values and redeploy"
say "This uses the Vercel CLI through npx. It asks you to log in and to link this folder to the project you made."
if confirm "Send the six values to Vercel (Production) now?"; then
  npx --yes vercel@latest link
  for k in SITE_URL SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET; do
    npx --yes vercel@latest env rm "$k" production --yes >/dev/null 2>&1 || true   # replace an old value on a re-run
    printf '%s' "${!k}" | npx --yes vercel@latest env add "$k" production >/dev/null && printf '  %s✓ set%s Vercel %s\n' "$GREEN" "$RESET" "$k"
  done
  if confirm "Redeploy production so the functions pick up the values?"; then npx --yes vercel@latest deploy --prod; fi
else
  SKIPPED+=("Vercel env vars: Project → Settings → Environment Variables, copy them from $ENV_FILE, then redeploy")
fi

stage "Test a purchase"
open_url "$SITE_URL/?shop=open"
step "In the shop, click Sign in, enter your email and click the link in the email."
step "Click Buy coins → a pack. On Stripe, tick the waiver box and pay with card 4242 4242 4242 4242, any future date, any CVC."
step "Back in the game, the Coins should appear within a few seconds."
step "Try Withdraw on the pack: the balance drops and Stripe shows a refund."
note "Coins don't show up? Check Stripe → Webhooks → your endpoint → recent deliveries, and Vercel → Logs."
pause "Press Enter to finish"

finish
